//
//	This file is automatically generated
//
switch (*DCOMMAND) {
	case 0:
		switch (*DFUNCTION) {
			case 0:
				DSPReset();
				break;
			case 1:
				*((uint32_t *)PARAMS) = TMRRead();
				break;
		}
		break;
	case 1:
		switch (*DFUNCTION) {
			case 0:
				CONWrite(*PARAMS);
				break;
		}
		break;
}
