# ***************************************************************************************
# ***************************************************************************************
#
#		Name : 		vectors.py
#		Author :	Paul Robson (paul@robsons.org.uk)
#		Date : 		22nd November 2023
#		Reviewed :	No
#		Purpose :	Creates the vector file for the kernel.
#
# ***************************************************************************************
# ***************************************************************************************

vectors = [
		"KReadCharacter",
		"KWriteCharacter",
		"KWaitMessage",
		"KSendMessage"
]

base = 0xFFFA-len(vectors)*3
print(";\n;\tThis file is automatically generated\n;")
print("* = ${0:0x}".format(base))

for v in vectors:
	print("\tjmp\t{0}".format(v))
