# ***************************************************************************************
# ***************************************************************************************
#
#		Name : 		vectors.py
#		Author :	Paul Robson (paul@robsons.org.uk)
#		Date : 		22nd November 2023
#		Reviewed :	No
#		Purpose :	Creates the vector file for the kernel.
#
# ***************************************************************************************
# ***************************************************************************************

vectors = [
		"KReadLine",
		"KReadCharacter",
		"KWriteCharacter",
		"KWaitMessage",
		"KSendMessage"
]

src = """
DoSendMessage .macro
	jsr 	SendMessage
	.endm

DoWaitMessage .macro
	jsr 	WaitMessage
	.endm
""".split("/r")

base = 0xFFFA-len(vectors)*3

h = open("build/_vectors.inc","w")
h.write(";\n;\tThis file is automatically generated\n;\n")
h.write("* = ${0:0x}\n".format(base))
for v in vectors:
	h.write("\tjmp\t{0}\n".format(v))
h.close()

s = open("../firmware/include/interface/memory.h").readlines()
s = [x for x in s if x.find("DEFAULT_PORT") > 0][0]
n = int(s[(s.find("DEFAULT_PORT")+12):].strip()[2:],16)

h = open("neo6502.inc","w")
h.write("ControlPort = ${0:04x}\n".format(n))
b = base
for v in vectors:
	h.write("{0} = ${1:04x}\n".format(v[1:],b))
	b += 3
h.write("\n")
for	l in src:
	h.write(l.rstrip()+"\n")
h.close()
