;
; File generated by cc65 v 2.19 - Git 4b9bf9bb9
;
	.fopt		compiler,"cc65 v 2.19 - Git 4b9bf9bb9"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_cmd
	.export		_main

.segment	"BSS"

_cmd:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$FF
	stz     _cmd
	stx     _cmd+1
	lda     #$01
	sta     ptr1
	stx     ptr1+1
	dea
	sta     (ptr1)
	lda     _cmd
	ldx     _cmd+1
	jsr     incax4
	sta     ptr1
	stx     ptr1+1
	lda     #$2A
	sta     (ptr1)
	lda     _cmd+1
	sta     ptr1+1
	lda     _cmd
	sta     ptr1
	lda     #$02
	sta     (ptr1)
	ldx     #$00
	txa
	rts

.endproc

