;
; File generated by cc65 v 2.18 - Git ece63f0
;
	.fopt		compiler,"cc65 v 2.18 - Git ece63f0"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_write
	.export		_main

.segment	"RODATA"

L001D:
	.byte	$68,$65,$6C,$6C,$6F,$20,$77,$6F,$72,$6C,$64,$0A,$00
L0019	:=	L001D+0

; ---------------------------------------------------------------
; int __near__ write (__near__ unsigned char *, unsigned int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_write: near

.segment	"BSS"

L0002:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	ldx     #$FF
	stz     L0002
	stx     L0002+1
	bra     L0006
L0008:	lda     L0002+1
	sta     ptr1+1
	lda     L0002
	sta     ptr1
	lda     (ptr1)
	bne     L0008
	lda     L0002+1
	sta     ptr1+1
	lda     L0002
	sta     ptr1
	lda     #$00
	ldy     #$01
	sta     (ptr1),y
	lda     L0002
	ldx     L0002+1
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	ina
	bne     L0013
	inx
L0013:	ldy     #$04
	jsr     staxysp
	lda     (regsave)
	ldy     #$04
	jsr     staspidx
	lda     L0002+1
	sta     ptr1+1
	lda     L0002
	sta     ptr1
	lda     #$02
	sta     (ptr1)
L0006:	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	jsr     stax0sp
	lda     regsave
	ora     regsave+1
	bne     L0008
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L0019)
	ldx     #>(L0019)
	jsr     pushax
	ldx     #$00
	lda     #$0C
	jsr     _write
	lda     #<(L001D)
	ldx     #>(L001D)
	jsr     pushax
	ldx     #$00
	lda     #$0C
	jsr     _write
	ldx     #$00
	txa
	rts

.endproc

