// ***************************************************************************************
// ***************************************************************************************
//
//      Name :      maths_other.config
//      Authors :   Paul Robson (paul@robsons.org.uk)
//                  Bill Auger
//      Date :      1st December 2023
//      Reviewed :  No
//      Purpose :   Maths "co-processor"
//
// ***************************************************************************************
// ***************************************************************************************


	FUNCTION 32 Number to Decimal
		MATHProcessDecimal(DCOMMAND);
	DOCUMENTATION
		Number to Decimal
		\newline TODO: describe the parameters

	FUNCTION 33 String to Number
		MATHConvertStringToNumber(DCOMMAND);
	DOCUMENTATION
		String to Number
		\newline TODO: describe the parameters

	FUNCTION 34 Number to String
		MATHConvertNumberToString(DCOMMAND);
	DOCUMENTATION
		Number to String
		\newline TODO: describe the parameters
