# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		makeprogram.py
#		Purpose :	Generate test program.
#		Date :		16th December 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,re,random
from tokens import *
from tokeniser import *

class TestProgram(object):
	#
	# 		Create a test program.
	#
	def __init__(self,lineCount = 500):
		self.variables = {}															# variable names
		self.identStore = IdentifierStore()  										# identifier storage
		for c in ["A","O","P","X","Y"]:  											# add defaults
			self.identStore.add(c)
			self.variables[c] = True
		self.tokenSet = TokenSet()  												# get all token names 
		self.tokenNames = self.tokenSet.getAllTokenNames()
		self.tokenWorker = Tokeniser(self.identStore)  								# tokeniser
		self.tokeniser = []  													
		self.sourceLines = []
		self.program = {}
		self.lineNumbers = {}

		random.seed()  																# set up the seed
		self.seed = random.randint(0,9999)
		#self.seed = 6325
		random.seed(self.seed)

		for i in range(0,lineCount >> 1): 											# generate line numbers
			self.lineNumbers[random.randint(1,60000)] = True
		self.lineNumbers = [x for x in self.lineNumbers.keys()]

		for i in range(0,max(10,lineCount >> 3)):  									# generate variable names
			vName = ""
			for c in range(0,random.randint(1,11)):
				vName = vName + (chr(random.randint(97,120)) if c % 2 == 0 else chr(random.randint(48,57)))
			if random.randint(0,2) == 0:
				vName += "$"
			if random.randint(0,2) == 0:
				vName += "("
			self.variables[vName] = True
		self.variables = [x for x in self.variables.keys()]

		for i in range(0,lineCount):  												# generate lines
			ln = self.lineNumbers[random.randint(0,len(self.lineNumbers)-1)]
			line = ""
			if random.randint(0,4) > 0:
				for e in range(0,random.randint(1,10)):
					e = self.createElement()
					if line != "":
						if self.cClass(line[-1]) == self.cClass(e[0]):
							line += " "
					line += e
			self.addLine(ln,line.strip())
	#
	# 		Create one program element
	#
	def createElement(self):
		n = random.randint(0,5)
		if n == 0:
			return str(random.randint(-320000,320000))
		elif n == 1:
			return str(random.randint(-999999,999999)/10)
		elif n == 2:
			return " ${0:X}".format(random.randint(0,123456))
		elif n == 3:
			return '"'+"".join([chr(random.randint(65,90)) for i in range(0,random.randint(0,7))])+'"'
		elif n == 4:
			return self.variables[random.randint(0,len(self.variables)-1)]
		elif n == 5:
			s = self.tokenNames[random.randint(0,len(self.tokenNames)-1)]
			if s.startswith("!!") or s == "'" or s == '$':
				s = self.createElement()
			return s
		else:
			assert False
		return str(n)	
	#
	#		Character class
	#
	def cClass(self,c):
		c = c.upper()
		return 1 if c == "_" or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") or c == "$" or c == "(" else 2
	#
	# 		Add a line of the program to the typed-in and the result
	#
	def addLine(self,lineNumber,code):
		self.sourceLines.append("{0} {1}".format(lineNumber,code))
		if code != "":
			self.program[lineNumber] = self.tokenWorker.tokenise(code)
		else:
			if lineNumber in self.program:
				del self.program[lineNumber]
	#
	# 		Render the type-in
	#
	def renderInput(self,h):
		h.write(";\n;\tThis file is automatically generated.\n;\n")
		h.write("; Seed = {0}\n;\n".format(self.seed))
		for l in self.sourceLines:
			h.write("\t.text\t{0},'{1}'\n".format(len(l),l))
		h.write("\t.byte\t0\n")
	#
	# 		Render what should be output.
	#
	def renderTokenised(self,h):
		h.write(bytes(self.identStore.render()))
		lNo = [x for x in self.program.keys()]
		lNo.sort()
		for l in lNo:
			line = [0,l & 0xFF,l >> 8] + self.program[l] + [self.tokenSet.getByName("!!end").getID()]
			line[0] = len(line)
			h.write(bytes(line))
		h.write(bytes([0]))

prg = TestProgram()
prg.renderInput(open("sources/generated/inputtoken.dat","w"))
prg.renderTokenised(open("build/token_test.dat","wb"))
