# ***************************************************************************************
# ***************************************************************************************
#
#      Name :      cursors.py
#      Authors :   Paul Robson (paul@robsons.org.uk)
#      Date :      21st March 2024
#      Reviewed :  No
#      Purpose :   Converts cursors to data (monochrome only at present)
#
# ***************************************************************************************
# ***************************************************************************************

import re,os,sys
from PIL import Image


class Cursor(object):
	def __init__(self,imageFile,xClick,yClick):
		self.click = (xClick,yClick)
		self.image = Image.open("scripts"+os.sep+"cursors"+os.sep+imageFile)
		assert self.image.size == (16,16)
		self.imageData = [0xFF] * 256
		self.name = imageFile[:-4].lower()
		for x in range(0,16):
			for y in range(0,16):
				p = self.image.getpixel((x,y))
				if p[3] > 128:
					self.imageData[x+y*16] = 7 if p[0]+p[1]+p[2] > 512 else 0
		ib = ",".join([str(x) for x in self.imageData])
		print("static const uint8_t {1}_cursor_data[] = {{ {0}}};\n".format(ib,self.name))

cursors = []
print("//\n//\tThis file is automatically generated.\n//")
Cursor("default.png",0,0)		
