# ***************************************************************************************
# ***************************************************************************************
#
#      Name :      cursors.py
#      Authors :   Paul Robson (paul@robsons.org.uk)
#      Date :      13th April 2024
#      Reviewed :  No
#      Purpose :   Converts cursors to data (2nd version)
#
# ***************************************************************************************
# ***************************************************************************************

import re,os,sys

def convert(n):
	n = n & 0x0F
	return 0xFF if n == 0 else n

src = [x for x in open("scripts/cursors/graphics.gfx","rb").read(-1)]
assert src[0] == 1 and src[1] == 0 and src[3] == 0
cursorCount = src[2]

print("//\n//\tThis file is automatically generated\n//\n")

print("#define CURSOR_IMAGE_COUNT ({0})\n".format(cursorCount))

cursorData = []
for c in src[256:]:
	cursorData.append(convert(c >> 4))
	cursorData.append(convert(c))

print("const uint8_t cursor_data[] = {")
print(",".join([str(x) for x in cursorData]))
print("};\n")

hitPoint = []
for i in range(0,cursorCount):
	hp = [8,8]
	if i == 0:
		hp = [4,0]
	if i in [4,9]:
		hp = [4,4]
	if i in [12,13,17,19]:
		hp = [0,15]
	if i in [15,20,21,22,23]:
		hp = [0,0]
	if i == 16:
		hp = [12,4]

	hitPoint += hp
print("const uint8_t cursor_hitPoint[] = {")
print(",".join([str(x) for x in hitPoint]))
print("};\n")

