# ***************************************************************************************
# ***************************************************************************************
#
#      Name :      prompt.py
#      Authors :   Paul Robson (paul@robsons.org.uk)
#      Date :      22nd November 2023
#      Reviewed :  No
#      Purpose :   Prompt creator (counts builds etc.)
#
# ***************************************************************************************
# ***************************************************************************************

import sys
#
#		This is the current version.
#
version = "0.11.0"

print("//\n//\tThis file is automatically generated\n//")
print("#define PROMPT \"Version {0}\\r\"".format(version))
