# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		makebuild.py
#		Purpose :	Create the build file
#		Date :		24th May 2023
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

import os,sys,math,re

include = []
assembler = []
for root,dirs,files in os.walk("src"):
	for f in files:
		if f.endswith(".asm"):
			assembler.append(root+os.sep+f)
		if f.endswith(".inc"):
			include.append(root+os.sep+f)

assembler.sort()
include.sort()

print(";\n;\tThis file is automatically generated.\n;")
for f in include+assembler:
	print('\t.include \"{0}\"'.format(f))	
	